kind = "web"
previewPath = "/"
title = "SmrtX_TODO"
version = "1.0.0"
id = "artifacts/smrtx-todo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24273

[services.development]
run = "pnpm --filter @workspace/smrtx-todo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smrtx-todo", "run", "build" ]
publicDir = "artifacts/smrtx-todo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24273"
BASE_PATH = "/"
